apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flask
  name: flask-deployment
  namespace: twitter-website
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: flask:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: 100m
            memory: 50Mi



---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: twitter-website
spec:
  selector:
    app: flask
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    # nodePort: 31819
