apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: celery
  name: celery-loc-deployment
  namespace: twitter-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery
  template:
    metadata:
      labels:
        app: celery
    spec:
      containers:
      - name: celery
        image: celery-location:latest
        command: 
        - "bash"
        - "-c"
        - "celery --app loc_module.tasks worker --loglevel=INFO --concurrency=2 -n worker1"
        # - "celery --app tasks worker --loglevel=INFO --concurrency=2 -n worker2"
        imagePullPolicy: Never
        ports:
        - containerPort: 5672
        resources:
          limits:
            cpu: 200m


