apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq-deployment
  namespace: twitter-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.9.26-management-alpine
        ports:
        - containerPort: 15672
          name: http        
        - containerPort: 5672
          name: amqp
        env:
        - name: RABBITMQ_DEFAULT_USER 
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: username
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: password


---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: twitter-website
spec:
  selector:
    app: rabbitmq
  type: NodePort
  ports:
  - protocol: TCP
    port: 15672
    targetPort: 15672
    nodePort: 30672
    name: http
  - protocol: TCP
    port: 5672
    targetPort: 5672
    name: amqp
