apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: celery
  name: celery-loc-deployment-1
  namespace: twitter-sentiment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery
  template:
    metadata:
      labels:
        app: celery
    spec:
      containers:
      - name: celery
        image: celery-location-oper:latest
        command: 
        - "bash"
        - "-c"
        - "celery --app loc_module.tasks worker --loglevel=INFO --concurrency=1 -n cityworker1 -Q loc_queue,send_loc"
        imagePullPolicy: Never
        ports:
        - containerPort: 5672
        resources:
          limits:
            cpu: 200m
            memory: 100Mi


