apiVersion: autoscaling.k8s.io/vibeta1
kind: VerticalPodAutoscaler
metadata:
  name: celery-hashtag-vpa
  namespace: twitter-sentiment
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: celery-hashtag-deployment-1
