apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq-deployment
  namespace: twitter-sentiment
spec:
  replicas: 3
  service:
    type: NodePort
  persistence:
    storageClassName: microk8s-hostpath
    storage: 1024Mi
  image: rabbitmq:3.9.26-management-alpine
  resources:
    requests:
      cpu: 100m
      memory: 500Mi
    limits:
      cpu: 200m
      memory: 1024Mi
  override:
    statefulSet:
      spec:
        template:
          spec:
            containers:
            - name: rabbitmq
              ports:
              - containerPort: 15672
                name: http        
              - containerPort: 5672
                name: amqp
              env:
              - name: RABBITMQ_DEFAULT_USER 
                valueFrom:
                  secretKeyRef:
                    name: rabbitmq-secret
                    key: username
              - name: RABBITMQ_DEFAULT_PASS
                valueFrom:
                  secretKeyRef:
                    name: rabbitmq-secret
                    key: password






