apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: celery
  name: celery-hashtag-deployment-4
  namespace: twitter-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery
  template:
    metadata:
      labels:
        app: celery
    spec:
      containers:
      - name: celery
        image: celery-hashtag:latest
        command: 
        - "bash"
        - "-c"
        - "celery --app hashtag_module.tasks worker --loglevel=INFO --concurrency=1 -n hashworker4@%h -Q hash_queue,send_data"
        imagePullPolicy: Never
        ports:
        - containerPort: 5672
        resources:
          limits:
            cpu: 100m
            memory: 100Mi


